In [6]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [6]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [7]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
model.fit(train_images, train_labels, epochs=10)

Epoch 1/10
60000/60000 [==============================] - 4s 67us/sample - loss: 2.8361 - acc: 0.6944
Epoch 2/10
60000/60000 [==============================] - 4s 62us/sample - loss: 0.6526 - acc: 0.7537
Epoch 3/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.5860 - acc: 0.7933
Epoch 4/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.5438 - acc: 0.8151
Epoch 5/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.5353 - acc: 0.8220
Epoch 6/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.5138 - acc: 0.8299
Epoch 7/10
60000/60000 [==============================] - 4s 62us/sample - loss: 0.5055 - acc: 0.8337
Epoch 8/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.5026 - acc: 0.8359
Epoch 9/10
60000/60000 [==============================] - 4s 60us/sample - loss: 0.4909 - acc: 0.8389
Epoch 10/10
60000/60000 [==============================] - 4s 61us/sample - loss: 

In [9]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

print('\nTest accuracy:', test_acc)

10000/10000 - 0s - loss: 0.5612 - acc: 0.8282

Test accuracy: 0.8282


In [10]:
predictions = model.predict(test_images)

In [12]:
predictions[0]

array([3.2301261e-05, 3.6385380e-08, 3.4753211e-09, 4.0520456e-07,
       2.6843050e-10, 9.8785320e-03, 9.6153656e-07, 4.4936474e-02,
       6.3255285e-03, 9.3882573e-01], dtype=float32)

In [131]:
test = 999
plt.bar([0,1,2,3,4,5,6,7,8,9],predictions[test])
test_labels[test]

7

In [24]:
train_images.shape

(60000, 28, 28)

In [7]:
train_images_reshaped = train_images.reshape((60000,28,28,1))
test_images_reshaped = test_images.reshape((10000,28,28,1))

In [29]:
test_images.shape

(10000, 28, 28)

In [35]:
train_images_reshaped[0].shape

(28, 28, 1)

In [43]:
train_images_reshaped.shape

(60000, 28, 28, 1)

In [44]:
train_labels

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [46]:
test_images_reshaped.shape

(10000, 28, 28, 1)

In [47]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [8]:
from tensorflow.keras.models import Sequential
from  tensorflow.keras.layers import Dense, Conv2D, Flatten

#create model
modelCNN = Sequential()
#add model layers
modelCNN.add(Conv2D(64, kernel_size=3, activation="relu", input_shape=(28,28,1)))
modelCNN.add(Conv2D(32, kernel_size=3, activation="relu"))
modelCNN.add(Conv2D(32, kernel_size=3, activation="relu"))
modelCNN.add(Flatten())
modelCNN.add(Dense(150, activation="relu"))
modelCNN.add(Dense(10, activation="softmax"))

In [9]:
#compile model using accuracy to measure model performance
modelCNN.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [10]:
#train the model
modelCNN.fit(train_images_reshaped, train_labels, validation_data=(test_images_reshaped, test_labels), epochs=10)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 20s 330us/sample - loss: 0.5606 - acc: 0.8506 - val_loss: 0.3457 - val_acc: 0.8769
Epoch 2/10
60000/60000 [==============================] - 12s 206us/sample - loss: 0.2671 - acc: 0.9015 - val_loss: 0.3303 - val_acc: 0.8825
Epoch 3/10
60000/60000 [==============================] - 12s 204us/sample - loss: 0.2044 - acc: 0.9225 - val_loss: 0.3625 - val_acc: 0.8745
Epoch 4/10
60000/60000 [==============================] - 12s 206us/sample - loss: 0.1623 - acc: 0.9401 - val_loss: 0.3583 - val_acc: 0.8951
Epoch 5/10
60000/60000 [==============================] - 12s 206us/sample - loss: 0.1250 - acc: 0.9536 - val_loss: 0.4245 - val_acc: 0.8937
Epoch 6/10
60000/60000 [==============================] - 13s 213us/sample - loss: 0.1025 - acc: 0.9629 - val_loss: 0.4168 - val_acc: 0.8919
Epoch 7/10
60000/60000 [==============================] - 12s 206us/sample - loss: 0.0813 - acc: 0.9712 

In [11]:
predictions_cnn = modelCNN.predict(test_images_reshaped)

In [12]:
np.round(predictions_cnn[0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [25]:
test = 11
plt.bar([0,1,2,3,4,5,6,7,8,9],predictions_cnn[test])
predictions_cnn[test]
test_labels[test]

5

In [88]:
plt.figure()
plt.imshow(test_images[10])
plt.colorbar()
plt.grid(False)
plt.show()

In [72]:
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']